# Generated by Django 6.0.1 on 2026-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name of the gym branch (Ex:  'Dhakkhin Khan GYM')", max_length=100, unique=True)),
                ('location', models.CharField(help_text="Address of the GYM (Ex:  ' 89/2, Dhakkhin Khan, Dhaka' )", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gym Branch',
                'verbose_name_plural': 'Gym Branches',
                'ordering': ['name'],
            },
        ),
    ]
